# Stage 1: Build and test the application
FROM maven:3.6.3-jdk-11-slim AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean test package


# Stage 2: Build and run the application
FROM tomcat:9.0.54-jdk11-openjdk-slim AS run
WORKDIR /usr/local/tomcat/webapps
COPY --from=build /app/target/accenture-techhub-0.0.1-SNAPSHOT.war ./ROOT.war
CMD ["catalina.sh", "run"]